export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL';

export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_APPOINTMENT_REQUEST = 'USER_APPOINTMENT_REQUEST';
export const USER_APPOINTMENT_SUCCESS = 'USER_APPOINTMENT_SUCCESS';
export const USER_APPOINTMENT_FAIL = 'USER_APPOINTMENT_FAIL';

export const USER_NEWAPPOINTMENT_REQUEST = 'USER_NEWAPPOINTMENT_REQUEST';
export const USER_NEWAPPOINTMENT_SUCCESS = 'USER_NEWAPPOINTMENT_SUCCESS';
export const USER_NEWAPPOINTMENT_FAIL = 'USER_NEWAPPOINTMENT_FAIL';


export const USER_DELETEAPPOINTMENT_REQUEST = 'USER_DELETEAPPOINTMENT_REQUEST';
export const USER_DELETEAPPOINTMENT_SUCCESS = 'USER_DELETEAPPOINTMENT_SUCCESS';
export const USER_DELETEAPPOINTMENT_FAIL = 'USER_DELETEAPPOINTMENT_FAIL';